---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "```ruby method ```"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "```ruby  meth```"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "```ruby ```"
  checked: false
name: Choice con código
